### ISSUE TITLE
Separate InstaScale out from default KFDEF

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/distributed-workloads#12]
Most users will always want MCAD available in their clusters, but they may not want InstaScale. We should separate out InstaScale into a separate overlay/manifest set so as to increase the flexibility of deployment.

**Comment by jbusche** [comment]
I wonder if it might be possible to add to the CR the image for these KFDEF?  For example, instead of using
```
quay.io/project-codeflare/instascale-controller:latest
```
I wonder if it'd be possible to override the image, cpu, memory so they could be changed just by editing the CR?
Like being able to override to this:
```
quay.io/project-codeflare/instascale-controller:v0.0.2
```

**Comment by jbusche** [comment]
Would it have it's own kfdef maybe?  Then when we're doing the E2E tests, we could check the existence of the instascale kfdef and make sure it's deleted/resources are gone.

**Comment by anishasthana** [comment]
1. Yeah, we could definitely add those to the CR.
2. re: the kfdef thing, yeah, that's an option!

**Comment by astefanutti** [comment]
Closing as it's become obsolete with the [operator redesign](https://github.com/project-codeflare/codeflare-operator/issues/279).
