### ISSUE TITLE
E2E Step 2: Install distributed workloads kfdef

### ISSUE THREAD

**Issue by Maxusmusti** [opendatahub-io/distributed-workloads#16]
- Check that MCAD pod comes up
 - Check that InstaScale pod comes up
 - Check that KubeRay pod comes up
 - Check for notebook imagestream

**Comment by anishasthana** [comment]
@jbusche this is done right?

**Comment by jbusche** [comment]
Yes @anishasthana, I just don't have the ability to assign or close these issues.
