### ISSUE TITLE
Add ability to manually override CodeFlare kfdef resource requirements

### ISSUE THREAD

**Issue by jbusche** [opendatahub-io/distributed-workloads#43]
Original ask:
```
We will want to update the deployment artifacts such that users can specify resource requirements within the kfdef itself.
```

Hopefully this is something that's supported in the current CRDs...

**Comment by jbusche** [comment]
Hi @anishasthana , I'm still messing with the kfdefs, mainly breaking things so far.  Looks to me like mcad resources are coming from [here](https://github.com/project-codeflare/codeflare-operator/blob/main/config/internal/mcad/deployment.yaml.tmpl#L37)  and aren't set to anything, so resources are an empty set for MCAD, currently.  

My original idea was to just edit the kfdef CR to update the resources or image tag, but looks like kubeflow utilizes kustomize to generate it from a combination of a tarball from the manifest combined with possible params.env/params.yaml overlays.  So now I'm thinking why we need to keep a complex set of params overlays rather than just updating it in the deployment source in lines [37](https://github.com/project-codeflare/codeflare-operator/blob/main/config/internal/mcad/deployment.yaml.tmpl#L37) and [28](https://github.com/project-codeflare/codeflare-operator/blob/main/config/internal/mcad/deployment.yaml.tmpl#L28).  Maybe we could have branches at various sizes small/med/large and the kfdef points to the correct codeflare-operator branch to generate the needed resource sizes?

Another option is to maybe figure out where the codeflare operator is storing the running image/resources and update them at the source, but I haven't figured out where they're stored... so when I manually update the CodeFlare deployments they revert back pretty quickly unless I turn off the Codeflare Operator.

**Comment by anishasthana** [comment]
The rationale behind this is allowing users to easily update the deployment from within the OpenShift Console. Directly editing the deployment source would require users to create a fork of the manifests and updating it.

**Comment by jbusche** [comment]
Alex mentioned that the direction of ODH going forward is to not use the kfdef.
Tried testing with ODH 2.0.0 and it looks, so these kfdef changes are unnecessary.

With the 2.0.0 release, you can change resources like this:
```
kubectl edit mcads mcad
```
or
```
kubectl edit instascales instascale
```
And then add this under the spec section:
```
  controllerResources:
    limits:
      cpu: "1"
      memory: 1G
    requests:
      cpu: "1"
      memory: 1G
```
