### ISSUE TITLE
Add make command to automatically update odh-manifests

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/distributed-workloads#60]
We should add a make command to automatically update the manifests and tests in odh-manifests. The make command should raise a PR. We implemented something similar to this for the CodeFlare repository.

One tricky thing we'll need to be careful about is that the basictest files have minor differences in odh-manifests and this repository. The minor differences are mainly around the paths.

**Comment by ChughShilpa** [comment]
Hi @anishasthana ,
Looking at the issue, i understand that for new release it is necessary to update some text files like in this PR:
https://github.com/opendatahub-io/odh-manifests/pull/851/files

Please correct me if my understanding is wrong.

And if you could share some documentation or links for reference that would be great :)

**Comment by ChughShilpa** [comment]
I mentioned above PR example in last comment for reference. I should have make it more descriptive and clear earlier.

The goal of this task is to bring manifest changes ( done in codeflare stack, ray and test ) of distributed-workloads  in sync with the odh-manifest. 
and we should consider the changes done after the last release.

@anishasthana , could you please confirm is this all needs to be done for this issue ?

**Comment by anishasthana** [comment]
Sorry, I meant to respond last week. That's accurate.
We want to do the following:
1.  Update the manifests to make sure they match
2. Update the compatibilty matrix so that it has the latest and greatest.

**Comment by ChughShilpa** [comment]
@anishasthana 
Adding make command in the source repo (i.e distributed workload) doesn't work for target repo (i.e odh-manifests) 
thus prepare github workflow for this.

**Comment by ChughShilpa** [comment]
PR - https://github.com/opendatahub-io/distributed-workloads/pull/70

**Comment by anishasthana** [comment]
Closed by #70
