### ISSUE TITLE
Add installation detail and Cleanup steps to the Quickstart

### ISSUE THREAD

**Issue by jbusche** [opendatahub-io/distributed-workloads#62]
The existing [Quick-Start.md](https://github.com/opendatahub-io/distributed-workloads/blob/main/Quick-Start.md) is a little confusing on a few steps for new users, and also lacks a Clean-Up section at the end.   I'd like to try to get both into the Quick-Start.
fyi: @asm582

**Comment by asm582** [comment]
Also, can we please add OpenShift versions that the instructions support

**Comment by jbusche** [comment]
Updated in [PR 73 ](https://github.com/opendatahub-io/distributed-workloads/pull/73)

**Comment by jbusche** [comment]
Oops, needs to be rebased... looking...

**Comment by jbusche** [comment]
Rebased and trying again with PR 73...

**Comment by jbusche** [comment]
Closing
