### ISSUE TITLE
Revise and update e2e integration tests

### ISSUE THREAD

**Issue by sutaakar** [opendatahub-io/distributed-workloads#63]
Verify that current tests in https://github.com/opendatahub-io/distributed-workloads/tree/main/tests cover expected use cases. In case of missing use cases implement them.
As part of the task revise current test implementation and evaluate if it is meaningful and easy to use, or if it has sense to refactor it (i.e. to match https://github.com/project-codeflare/codeflare-operator/tree/main/test/e2e).

**Comment by amsharma3** [comment]
Thanks for this one Karel. Can we link, mention the "expected use cases" (in description) here somehow, that will be very helpful

**Comment by sutaakar** [comment]
@amsharma3 Need to discuss that with Anish. In general I would say that the scenarios currently available in ODH repo should be enough.
Thinking about preparing one UI test checking that UI flow works as expected.

**Comment by sutaakar** [comment]
Done.
