### ISSUE TITLE
Add make command to automatically install ODH and CodeFlare on OpenShift

### ISSUE THREAD

**Issue by sutaakar** [opendatahub-io/distributed-workloads#64]
Currently the installation of ODH and CodeFlare is done manually, see [quickstart](https://github.com/opendatahub-io/distributed-workloads/blob/main/Quick-Start.md).

Purpose of this task is to create a make command which would setup ODH and CodeFlare on available OpenShift instance.
The command should ideally target the new ODH operator.

This automation will be used in tests to setup the environment.

**Comment by anishasthana** [comment]
@sutaakar take a look at https://github.com/opendatahub-io/distributed-workloads/pull/57. It seems to be related.

**Comment by sutaakar** [comment]
Yes, it seems to address this issue.

**Comment by sutaakar** [comment]
Closing as it was implemented in https://github.com/opendatahub-io/distributed-workloads/pull/57
