### ISSUE TITLE
Use Tagged version of codeflare-sdk stack

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/distributed-workloads#80]
We broke odh-manifests CI earlier this week when we had the latest release of the CodeFlare stack. This was due to some backwards incompatible changes in the codeflare-sdk. We should update the deployed manifests such that it's always a tagged version of the images being used.

**Comment by anishasthana** [comment]
fyi @LaVLaS @Maxusmusti

**Comment by sutaakar** [comment]
@anishasthana I see that something similar was addressed in https://github.com/opendatahub-io/distributed-workloads/pull/83 , should this issue be closed?

**Comment by anishasthana** [comment]
Ah,  yes!
